<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.lowes.training</groupId>
    <artifactId>java-full-stack-engineering</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>comprehensive-java-programming</module>
        <module>project03</module>
        <module>project02</module>
        <module>apache-maven-learning</module>
        <module>software-design-and-engineering</module>
        <module>software-design-and-engineering/logging-and-monitoring</module>
        <module>milestone03-mastering-spring-boot</module>
        <module>milestone03-mastering-spring-boot/m05-data-persistence-with-spring-data-jpa</module>
        <module>milestone03-mastering-spring-boot/m06-testing-spring-boot-applications</module>
        <module>milestone03-mastering-spring-boot/m07-production-ready-features</module>
        <module>milestone03-mastering-spring-boot/m08-security-with-spring-security</module>
    </modules>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.3.0</version>

                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>org.lowes.training.BrowserAutomation</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>

        </plugins>
    </build>

</project>